language: cpp
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libqt4-dev qt4-qmake cmake

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug
  - make
  - tests/QTestLibCocktailsTest
